# secrets.yml
#

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_password: <%= ENV["MANDRILL_PASSWORD"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_password: <%= ENV["MANDRILL_PASSWORD"] %>


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_password: <%= ENV["MANDRILL_PASSWORD"] %>
